# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo" # Rust/Cargo ecosystem
    directory: "/" # Location of Cargo.toml (project root)
    schedule:
      interval: "weekly"
    # Optional: Group updates to reduce PR noise
    groups:
      dev-dependencies:
        patterns:
          - "*"
        dependency-type: "development"
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"