services:
  watchtower:
    image: containrrr/watchtower
    container_name: leveling-education-framework-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    image: spark156/leveling-education-framework:latest
    container_name: leveling-education-framework
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: ${HOSTS}
      caddy.reverse_proxy: "{{upstreams 3000}}"

networks:
  caddy:
    external: true