version: "3.9"

services: 
  watchtower:
    image: v2tec/watchtower
    container_name: leveling-education-framework-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  frontend:
    image: spark156/leveling-education-framework-frontend:latest
    container_name: leveling-education-framework-frontend
    build:
      context: frontend
      target: production
    networks:
      - caddy
    labels:
      caddy: ${HOSTS}
      caddy.reverse_proxy: "{{upstreams}}"
  
  backend:
    image: spark156/leveling-education-framework-backend:latest
    container_name: leveling-education-framework-backend
    build: 
      context: backend
      target: production
    networks:
      - caddy
    labels:
      caddy: ${HOSTS}
      caddy.handle_path: /api/v1/*
      caddy.handle_path.0_rewrite: "* {uri}"
      caddy.handle_path.1_reverse_proxy: "{{upstreams}}"
    
networks:
  caddy:
    external: true

