version: '3.8'

services:
  frontend:
    container_name: hboi-kubus-killer-frontend
    build: 
      context: frontend
      target: production
    labels:
      traefik.http.services.frontend.loadbalancer.server.port: 80
